"""initial schema

Revision ID: 43eabfbacfc3
Revises: 
Create Date: 2026-01-10 23:53:11.121077
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43eabfbacfc3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
