"""enhance_roles_and_tenants_tables

Revision ID: 670e29479383
Revises: f7b592ca7922
Create Date: 2026-01-11 08:26:05.019832
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '670e29479383'
down_revision = 'f7b592ca7922'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enhance roles table
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.JSON(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('is_system_role', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE roles SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE roles SET is_system_role = true WHERE is_system_role IS NULL")
    op.execute("UPDATE roles SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE roles SET updated_at = NOW() WHERE updated_at IS NULL")
    
    # Make columns NOT NULL after setting defaults
    op.alter_column('roles', 'is_active', nullable=False)
    op.alter_column('roles', 'is_system_role', nullable=False)
    op.alter_column('roles', 'created_at', nullable=False)
    op.alter_column('roles', 'updated_at', nullable=False)
    
    # Enhance tenants table
    op.add_column('tenants', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('organization_name', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('plan_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('billing_address', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('max_users', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('max_projects', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE tenants SET is_trial = false WHERE is_trial IS NULL")
    
    # Make is_trial NOT NULL after setting defaults
    op.alter_column('tenants', 'is_trial', nullable=False)
    
    # Create indexes for tenants (using raw SQL to handle if_not_exists)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_tenants_slug ON tenants (slug) WHERE slug IS NOT NULL")
    op.execute("CREATE INDEX IF NOT EXISTS ix_tenants_name ON tenants (name)")
    
    # Create indexes for user_tenant_roles (using raw SQL to handle if_not_exists)
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_tenant_roles_role ON user_tenant_roles (role)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_tenant_roles_tenant_id ON user_tenant_roles (tenant_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_tenant_roles_user_id ON user_tenant_roles (user_id)")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tenant_roles_user_id'), table_name='user_tenant_roles')
    op.drop_index(op.f('ix_user_tenant_roles_tenant_id'), table_name='user_tenant_roles')
    op.drop_index(op.f('ix_user_tenant_roles_role'), table_name='user_tenant_roles')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_column('tenants', 'deleted_at')
    op.drop_column('tenants', 'trial_ends_at')
    op.drop_column('tenants', 'is_trial')
    op.drop_column('tenants', 'max_projects')
    op.drop_column('tenants', 'max_users')
    op.drop_column('tenants', 'billing_address')
    op.drop_column('tenants', 'subscription_expires_at')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'plan_id')
    op.drop_column('tenants', 'features')
    op.drop_column('tenants', 'settings')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'organization_name')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'slug')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'is_system_role')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
